credentials:
  usernames:
    vivek.gaur@beigene.com:
      email: vivek.gaur@beigene.com
      name: Vivek Gaur
      password: 1qaz!QAZ 
    kartik.mehboobani@begouconsulting.com:
      email: kartik.mehboobani@begouconsulting.com
      name: Kartik Mehboobani
      password: 3edc#EDC 
    sudeeksha.kura@beigene.com:
      email: sudeeksha.kura@beigene.com
      name: Sudeeksha Kura
      password: 2wsx@WSX
    Vineet.mishra@beghouconsulting.com:
      email: Vineet.mishra@beghouconsulting.com
      name: Vineet Mishra
      password: 4rfv$RFV
cookie:
  expiry_days: 30
  key: HawkAI_UI # Must be string
  name: HawkAI
